### ISSUE TITLE
Unclear licensing

### ISSUE THREAD

**Issue by ViviCoder** [google/re2j#112]
I would like to package RE2/J for Debian Linux, but it is not clear whether or not it is distributable.
The license file acknowledges the original work by the Go authors, but it does not provide any information on the actual license/copyright of the Java port.
In addition, some files, such as ` java/com/google/re2j/Matcher.java`, do not even refer to a license, only to a copyright.
I am afraid the packaging cannot not go further until this is clarified.

**Comment by ViviCoder** [comment]
Do you plan to make a new release soon? It would allow me to package RE2J into Debian without using a complicated upstream version number.

**Comment by sjamesr** [comment]
Hi @ViviCoder, I've published RE2/J 1.5. It contains no changes other than adequate license headers in all source files, plus changes to the build system to make sure that these don't get forgotten in the future.

**Comment by ViviCoder** [comment]
Hi @sjamesr, thanks for acting so quickly. I will now work on the Debian package.
