### ISSUE TITLE
API to list named-capture-groups

### ISSUE THREAD

**Issue by cyberbeat** [google/re2j#125]
At the moment it is a flaw of java regex, that it is not possible to enumerate named-capture groups. It would be a reason to switch to re2j for me alone of that. For example something like

`
Map<String,String> getNamedGroups()
`

**Comment by j4ckcyw** [comment]
I run into this too. [RE2](https://github.com/google/re2j/blob/master/java/com/google/re2j/RE2.java#L122) already exposes this as public, but Pattern is not. It would be easy to submit a pull request. But I just want to make sure there is no pushback / concern?

**Comment by j4ckcyw** [comment]
This can be closed :)
