### ISSUE TITLE
Incorrect behavior for Pattern::split

### ISSUE THREAD

**Issue by mahmoudimus** [google/re2j#131]
## How to reproduce

```
jshell> com.google.re2j.Pattern.compile("x*").split("foo")
$1 ==> String[4] { "", "f", "o", "o" }

jshell> java.util.regex.Pattern.compile("x*").split("foo")
$2 ==> String[3] { "f", "o", "o" }
```

## Versions
- `java 11.0.10`
- `re2j 1.5`

Should I try for a PR?

**Comment by sjamesr** [comment]
Interesting, RE2J and java.util.regex evidently differ on how to handle leading zero-length matches. I guess we should bring RE2J into line. I'd appreciate a pull request if it isn't too much trouble for you.

Thanks for reporting this.

**Comment by sjamesr** [comment]
@adonovan would you be able to take a look? Unfortunately this change causes RE2J's Pattern.split method to be textually quite different from Go's. Also, it changes the behavior of split to omit empty matches, which brings it into line with `java.util.regex` but probably not with RE2 (I didn't test the behavior of other regex impls).
