### ISSUE TITLE
Publish API documentation

### ISSUE THREAD

**Issue by hickford** [google/re2j#154]
Hi. Is any documentation published for the Java library API?

* C++ library has partial documentation on its wiki  https://github.com/google/re2/wiki/CplusplusAPI
* Go regexp package has comprehensive documentation at https://pkg.go.dev/regexp

**Comment by sjamesr** [comment]
The javadoc is pretty good, see https://javadoc.io/doc/com.google.re2j/re2j/latest/index.html.

Does that help?
