### ISSUE TITLE
Support (?<name>expr) named capturing groups format

### ISSUE THREAD

**Issue by geniusjoe** [google/re2j#163]
I'm a kafka developer and I maintain some kafka clusters in my company. I often expose an interface to my kafka users, so that they can post a regular expression and analyse kafka records by using kafka transform. The analysed records can be used in kafka connect and send to other sink services. 

Nowadays I think `(?<name>expr)` capturing group syntax becomes more popular, and my kafka users prefer to use this syntax instead of `(?P<name>expr)`. But I found that `re2j` only support `(?P<name>expr)` named group format refer to code comment below: 
>   In both the open source world (via Code Search) and the
>   Google source tree, `(?P<name>expr)` is the dominant form,
>   so that's the one we implement.  One is enough.

So should we support `(?<name>expr)` syntax? I think if we support this feature, what we only need to do is add this prefix, and change skip substring length in `com/google/re2j/Parser.java/parsePerlFlags` function. If we can support this syntax, I can make a pr.
![image](https://user-images.githubusercontent.com/37236056/208716353-bdcc515d-5743-485c-9dba-629bd177b852.png)

**Comment by rockwotj** [comment]
We recently lost a fair bit of time debugging to realize the issue is that we forgot the `P`.

**Comment by junyer** [comment]
FYI, this was done in commit 9b3f05296e365e47b152054cbb9d82c205ea4dce.

**Comment by geniusjoe** [comment]
> FYI, this was done in commit [9b3f052](https://github.com/google/re2j/commit/9b3f05296e365e47b152054cbb9d82c205ea4dce).

Thx! This is really what I need.
