### ISSUE TITLE
how to get matched names

### ISSUE THREAD

**Issue by ytcpub** [google/re2j#37]
like  (?P\<volume\>\d+)sf(d|e)
how can I get by name "volume"

**Comment by MasseGuillaume** [comment]
`Matcher.group(String)` is not supported see: https://github.com/google/re2j#caveats

**Comment by MasseGuillaume** [comment]
@sjamesr It's actually really easy to implement: https://github.com/scala-native/re2s/commit/9a40319b21629b27b4fb2b9685cdc6428da26003

**Comment by sjamesr** [comment]
I had a go at it in re2j, see https://github.com/google/re2j/commit/2eb2f0eef46ce11a4daaeae776dc95d2c2b4d20a. Not sure if my impl is correct though.
