### ISSUE TITLE
What about a new release?

### ISSUE THREAD

**Issue by speak2me** [google/re2j#45]

**Comment by sjamesr** [comment]
will do tomorrow

**Comment by martin-a** [comment]
Not sure about the review state of those PR but as they seem to improve performance would be nice to include them in this new release if possible
#35 #36

**Comment by brewkode** [comment]
@sjamesr Hey, are you guys planning for a new release? Happened to stumble upon this and want to see if I can pick up the latest set of changes?

**Comment by sjamesr** [comment]
Done, 1.2 is now out.
