### ISSUE TITLE
Thoughts on synchronized access on RE2 instances

### ISSUE THREAD

**Issue by nicktrav** [google/re2j#46]
We've recently been doing some profiling on one of our applications that uses `re2j` quite heavily, and we're noticing a decent amount of thread contention coming from `RE2` when doing concurrent patten matching (i.e. multiple threads using the same `Pattern` instance).

Both `RE2#get` and `RE2#put` synchronize access on the monitor to obtain either a cached `Machine` instance or instantiate a new one if there are none that already exist.

Here's a small example that when run demonstrates the blocking thread behavior:

```java
public class ThreadContentionExample {

  private static final int THREADS = 20;
  private static final Pattern PATTERN = Pattern.compile("\\w+://.*");

  public static void main(String ...args) throws InterruptedException {
    Thread[] threads = new Thread[THREADS];
    for (int i = 0; i < THREADS; i++) {
      Thread thread = new Thread() {
        @Override public void run() {
          while (true) {
            PATTERN.matcher("https://www.google.com").matches();
          }
        }
      };
      thread.start();
      threads[i] = thread;
    }

    for (Thread thread : threads) {
      thread.join();
    }
  }
}
```

The thread profile (via YourKit) looks as follows:

![screen shot 2018-02-12 at 11 00 38 am](https://user-images.githubusercontent.com/804457/36114178-0da990ee-0fe4-11e8-9ac0-ec24f0a9d444.png)

I did some JMH profiling with various other concurrent data structures, but it seems like all have _slightly_ worse off performance than the current implementation at lower thread counts (within error bounds anyway). A `ConcurrentLinkedQueue` or `Dequeue` seems to be slightly more performant at higher thread counts. However, even if they _were_ better, many of these more "exotic" classes are not available in GWT anyway or they're at a higher JDK language level ([re2j uses 1.6 features now](https://github.com/google/re2j/blob/master/pom.xml#L63)), so I think that precludes them from use.

That said, I was wondering if there were any thoughts how this synchronization bottleneck could be removed, or at least improved a little, in the case that there are many threads accessing the same `Pattern` instance?

Our current approach is to just use `ThreadLocal` `Pattern`s in our application code (as we have bounded thread pools). I see that the `ThreadLocal` approach was adopted in re2j too, but it lead to some memory leaks, so it was [reverted](https://github.com/google/re2j/pull/43).

This definitely _isn't_ a dealbreaker for us, and it's not really a bug either, just food for thought.

`Re2j` has been great! Thanks!

**Comment by arnaudroger** [comment]
I was looking at that. and also it would be possible to have a non-locking structure to keep track of the cache it's quite complicated and error-prone. It might be easier to allow people to get non Thread safe instance that avoid the complication of managing a pool of Machine if they are ready to have one per thread.

**Comment by charlesmunger** [comment]
I believe #121  will fix this.
