### ISSUE TITLE
whitespace character class ('\s') matching different characters than java Pattern

### ISSUE THREAD

**Issue by martin-a** [google/re2j#50]
The java [Pattern](https://docs.oracle.com/javase/8/docs/api/java/util/regex/Pattern.html) API defines `\s` as matching `[ \t\n\x0B\f\r]`

Unfortunately Re2j the current implementation (based on [Re2](https://github.com/google/re2/wiki/Syntax) syntax) does not match \x0B (Vertical tab) with the `\s` character class

Fixing it directly in the code inside CharGroup.java would seems straightforward, unfortunately this file is generated by the make_perl_groups.pl script, which resolves classes directly from perl.

Maybe instead of using the `make_perl_groups.pl` script that resolves classes from perl it would be preferable to have a script in Java that would resolves classes similarly (but from Java).

**Comment by alandonovan** [comment]
The authority for this decision is not Perl but Unicode; Perl is just the vehicle.  Unicode specifies that LINE_TABULATION is a separator but not a space:
    ftp://unicode.org/Public/5.1.0/ucd/UnicodeData.txt
Here's the same information in a friendlier format:
  http://www.fileformat.info/info/unicode/char/000B/index.htm

**Comment by martin-a** [comment]
I see your point.
Maybe Java relies on the the Unicode [whitespace](https://en.wikipedia.org/wiki/Unicode_character_property#Whitespace) character property ? (although in ASCII range `\xA0` is missing ...) The problem is probably on java specifications side.

I know re2j does not have full compatibility with java native regex, but I though it would have been good if supported char class had the same meaning.

Similarly in perl (re2j): `\v` matches `\x0B` where in java regex syntax `\v` matches `[\n\x0B\f\r\x85\u2028\u2029]`

_Note: I do not consider this whole issue as really problematic; most users do not care about matching or not the Vertical tab character._

**Comment by alandonovan** [comment]
It can't be compatible with Java's regexps and the RE2 spec where the two contradict each other. I consider it working as intended, and agree with your footnote.
