### ISSUE TITLE
Question about supported features

### ISSUE THREAD

**Issue by ftarlao** [google/re2j#51]
Are lookaround operators supported by re2j?
Possessive quantifiers? (e.g.: ++)
Regards

**Comment by ftarlao** [comment]
Only a kind PING.. no hurry

**Comment by martin-a** [comment]
No neither are supported.
You can look at syntax supported by RE2 here: https://github.com/google/re2/wiki/Syntax (re2j should have identical limitations)

**Comment by ftarlao** [comment]
Thanks, regards
