### ISSUE TITLE
re2j vs java.util.regex PatternSyntaxException behavior discrepency.

### ISSUE THREAD

**Issue by zzbennett** [google/re2j#7]
Not a huge issue but when I tested out re2j, some of my unit tests that expect a PatternSyntaxException failed with re2j as re2j did not consider the regex to be invalid whereas they pass with java.util.regex.

An example regex that causes the PatternSyntaxException in java.util.regex but not in re2j is:

``` java
.*field1=([^|]*)\\|field2=([^|]*).*(
```

**Comment by sjamesr** [comment]
RE2J now correctly rejects this pattern
