### ISSUE TITLE
proposal: port RE2's CoalesceWalker to RE2/J

### ISSUE THREAD

**Issue by junyer** [google/re2j#8]
https://github.com/google/re2/commit/b77e1a42b36501870b046a0f691e2aedbc2495af added an optimisation to RE2. I'm offering to port this to RE2/J for the sake of feature parity.

**Comment by junyer** [comment]
(FWIW, I made a similar offer to the Go project as per https://github.com/golang/go/issues/11855.)

**Comment by adonovan** [comment]
Thanks, but the goal of RE2/J, like Go's REs, is not maximum performance but asymptotic performance, simplicity, and clarity.  Keeping this code base consistent with Go's one makes maintenance much easier.
