### ISSUE TITLE
Support for binary-mode matching?

### ISSUE THREAD

**Issue by steveniemitz** [google/re2j#84]
This might be related to issue #17.  The C++ implementation of re2 supports matching binary data (using a Latin1 encoding I believe) rather than unicode strings, including supporting \C as "match any byte".

It would be awesome to have support for this in this java port as well, are there any plans to ever add support for it?  I've hacked in support for these in my own branch to support my requirements but I'm not sure how well it'd work in a general case.

**Comment by j4ckcyw** [comment]
@steveniemitz are you still looking into it?

I see two ways of doing this:
1. implement CharSequence backed by a byte array.
2. expose RE2J's matchUTF16 method to Pattern/Matcher.

@sjamesr,  @alandonovan any preference which one is better?

**Comment by j4ckcyw** [comment]
Example of 1. https://www.javamex.com/tutorials/memory/ascii_charsequence.shtml Note: you would construct this with a byte[] or ByteBuffer instead of a String, since the point is to avoid serializing the original byte to a String before matching.

**Comment by steveniemitz** [comment]
I've had a fork since a little after I wrote this bug that implements it, but its not compatible with non-binary-mode (since I've only ever cared about binary).  There's a go fork of re2 also now that implements it. https://github.com/rsc/binaryregexp
